apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::464117734641:role/eksctl-cluster123-nodegroup-clust-NodeInstanceRole-5VB6FNDK45J4
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - usersarn: arn:aws:iam::464117734641:user/roboshop-project
      username: roboshop-project    
kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-27T23:06:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1199"
  uid: 54ef9f45-0d64-451a-a05c-3a457acf7716